### ISSUE TITLE
Release 0.0.5

### ISSUE THREAD

**Issue by fonsp** [JuliaWeb/Hyperscript.jl#43]
The last release, `0.0.4`, was on Nov 10, 2020, and there have been 14 commits by 7 contributors since then:

https://github.com/JuliaWeb/Hyperscript.jl/compare/v0.0.4...master

Can we release 0.0.5? @SimonDanisch We need https://github.com/JuliaWeb/Hyperscript.jl/pull/29 for improving Pluto support in JSServe.

**Comment by SimonDanisch** [comment]
Alright lets do this ;)
